title: Les Artistes Inn
description: An inspired place to stay
markdown: kramdown
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
title_left: Les Artistes Inn
subtitle_alternate: And Secret Garden Inn of Del Mar
subtitle_left: An Inspired Place to Stay
address_left: 944 Camino Del Mar
city_left: Del Mar, CA 92014
email_middle: lesartistesinn@gmail.com
phone_middle: (858) 755-4646
title_right: Secret Garden Inn
subtitle_right: Of Del Mar, Bed & Breakfast
address_right: 1140 Camino Del Mar
city_right: Del Mar, CA 92014
# google_analytics: UA-xxxxxxxx-2
