name: Publish Website

on: 
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "publish"
  cancel-in-progress: true

jobs:
  build:
    if: github.repository == 'Les-Artistes-Inn/LesArtistesInn.com'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Download Zola
        run: curl -fLsS "https://github.com/getzola/zola/releases/download/v0.19.1/zola-v0.19.1-x86_64-unknown-linux-gnu.tar.gz" | tar xzf - -C /usr/local/bin
      - name: Verify Zola binary
        run: echo "5a08302389d1ac6a54391984d414eba01b2b7b23d9ab410f51e87756ed0563bb  /usr/local/bin/zola" | shasum -a 256 -b -c --strict
      - name: Build website
        run: zola build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}